### ISSUE TITLE
Feature: JSON support

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-client-go#115]
We should add simple JSON support to read and write json.

Open question:
Should the user be able to unmarshal data into concrete structs?

**Comment by sejr** [comment]
> Should the user be able to unmarshal data into concrete structs?

At least for right now, it might be easier to just use a `map[string]interface{}`.

@steebchen  the Go client generator currently converts `Json` Prisma model types to an undefined `Json` Go type, which causes errors when building generated packages.

I'd also recommend calling this generated type `JSON` otherwise you'll get a warning from `go-lint`.

**Comment by steebchen** [comment]
@sejr What about when setting the json field? How could one do that?

**Comment by sejr** [comment]
Do you have an example of what you're think of? I'm not sure I'm following.

If I specify a `Json` type in my Prisma schema, I would want to handle it the same way I receive a JSON response body from an HTTP request. I'd get the bytes, then attempt to marshal into a Go struct that I've defined with struct tags.

Obviously, I could define another schema model instead of having Json, but I intentionally use that type _because_ it's an "unknown" (for the most part).

**Comment by steebchen** [comment]
> I'd get the bytes, then attempt to marshal into a Go struct that I've defined with struct tags.

But that would not work with a `map[string]interface{}`, would it?

That's why we could use `json.RawMessage`, for example. Does that make sense?

**Comment by sejr** [comment]
Didn’t know about `json.RawMessage` - yeah I think that would be better.

**Comment by steebchen** [comment]
What do you think makes sense as an input? also json.RawMessage, or does interface{} make more sense?

**Comment by sejr** [comment]
As an input I think I’d personally prefer just being able to pass in an interface. The generated code could return an error if that interface was unable to be marshaled into JSON.

**Comment by sejr** [comment]
> This sounds good to me. It just introduces a lot of work for me, since this would be the first data type which maps to a different data types depending on it's used as an input or an output type. It would be way easier to just use json.RawMessage everywhere, but then the user has to do a json.Marshal for custom structs before they can be given to the prisma client.

I'd be okay with just using `RawMessage` everywhere, honestly.
