### ISSUE TITLE
Add a E2E test to know when the binary breaks the API

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-go#143]

**Comment by steebchen** [comment]
The first step (testing zeit/pkg) is done via https://github.com/prisma/e2e-tests/pull/424 and https://github.com/prisma/e2e-tests/pull/425.

About testing the whole repo via an automated way is tricky, as it would involve a lot more complex stuff like auto publishing prisma binaries, auto updating them  in this repo via pull requests, and considering different branches for latest vs. dev releases.

**Comment by matthewmueller** [comment]
Cool, do you mind explaining how testing zeit/pkg works? And what we're testing and what we're not testing with this change?

My thinking was we'd have one of those (in)famous Luca actions where every 5 minutes you'd check for an update on engines, download it and run `go test`. Does that not work?

**Comment by steebchen** [comment]
zeit/pkg just tests if everything works fine when running simple commands with a built binary. It feels a bit too simple but this part broke tons of times in the past (and it's broken right now), so it's definitely a good first step.

**Comment by matthewmueller** [comment]
Great. I love first steps :-D 

> My thinking was we'd have one of those (in)famous Luca actions where every 5 minutes you'd check for an update on engines, download it and run go test. Does that not work?

Is this just more work but planned? Or does this idea not make sense?

**Comment by steebchen** [comment]
My main concern is how much value whatever solution we can build provides.
Do we want to bump this directly in this repo with each alpha? Then we'd need to use the action, bump this, and introduce a dev branch in this repo. It would only be used to notify us if something stops working (because otherwise we'd need PRs to the main branch for this change, which would be very cool but also noisy and a lot more work), but if it's in that dev channel, we'd need a slack notifier. However, often we introduce breaking changes which I know about, but couldn't get to yet. Then for each alpha update the slack feed gets spammed that the build fails. I'm not sure what the best solution here is which is not so relaxed that I'll not notice when something fails, but also not so strict that I'll get overwhelmed by it.

**Comment by matthewmueller** [comment]
Sounds good. The important thing is that the people don't install an incompatible version of the query engine. 

As long as we can control when this happens and we have tests that won't let us release without first checking compatibility with the engine, then we should be good.

**Comment by steebchen** [comment]
Yes, it has hardcoded and has to be updated manually via a PR with passing tests by me. And even when it's successfully merged to master, it still has to be released to a tag so go modules users will get that update (expect if they explicitly re-install with @master).

**Comment by matthewmueller** [comment]
Great! Can this be closed then?

**Comment by steebchen** [comment]
Not sure. I guess I'll close and re-open if I have new plans for this.
