### ISSUE TITLE
Reduce code verbosity for conditional filters

### ISSUE THREAD

**Issue by maaft** [prisma/prisma-client-go#203]
Currently for database filters require to pass an actual integer value for filtering:
```golang

var upperBound int

users, err := r.Client.User.FindMany(
   db.User.NumPosts.GT(upperBound),
).Exec(ctx)
```
When offering a variety of filtering options via an API, the user might or might not set certain filter options (equals, gt, gte, lt, lte, .... ). These filter options are then `nil` in golang.

Currently I have to check all possible combinations of filter options and write the corresponding query to my database which leads to **huge** repeated code.

tl;dr: Can we please have nullable filters where we can just do:

```golang
var equalsParam *int
var gtParam *int
var gteParam *int
var ltParam *int
var lteParam *int

users, err := r.Client.User.FindMany(
   db.User.NumPosts.Equals(equalsParam),
   db.User.NumPosts.GT(gtParam),
   db.User.NumPosts.GTE(gteParam),
   db.User.NumPosts.LT(ltParam),
   db.User.NumPosts.LTE(lteParam),
  ...
).Exec(ctx)
```

`nil` ops could just be ignored and the query could throw an error when an impossible combination of operations is used.

The same might be useful for String and Float filters.

**Comment by steebchen** [comment]
For other types we use MethodOptional, e.g. EqualsOptional. It's a bug that they are missing for the number operations.

**Comment by maaft** [comment]
That sounds great, thank you!

**Comment by steebchen** [comment]
EqualsOptional exists, but only on fields which are actually optional/nullable:

https://github.com/prisma/prisma-client-go/blob/fddd26d29b3d9bdef6d9c75edd4fcc4109db829b/test/projects/types/types_test.go#L363

It's really only available for Equals, I'll add optional variations to the other methods as well.

**Comment by maaft** [comment]
What about optional Update-Set Params?

E.g.
```golang
var nameParam *string
var descriptionParam *string

user, err := r.Client.User.FindOne(
   db.User.ID.Equals(ID),
).Update(
   db.User.Name.SetOptional(nameParam),
   db.User.Description.SetOption(descriptionParam),
).Exec(ctx)
```

**Comment by steebchen** [comment]
I think what you're actually asking for is an "undefined" filter, not a null filter. You don't want to filter for results which are null, you want to filter depending on whatever value is set or not. I think we need to have a broader discussion first how on how we want to handle this, because it affects the syntax. In theory, we could use a double pointer – one for whether the parameter is optional (javascript `undefined` or graphql "not defined"), and one for whether the user wants to search for fields which are null (javascript or graphql `null`).

**Comment by steebchen** [comment]
One solution might be to just introduce more methods. So for an optional field (which can be `null`), you could have the following query methods:

```go
 // query for names "doe"
db.User.Name.Equals("doe")

// query for name == *str, or null if str == nil
// this is the same as "EqualsOptional" right now, just renamed to EqualsNull for clarification
var str *string = x
db.User.Name.EqualsNull(str)

// query for name == *str, but if str == nil do NOT filter by anything
var str *string = x
db.User.Name.EqualsUndefined(str)

// in theory you could want to query for both, so here we go:
db.User.Name.EqualsNullOrUndefined(str)
```

The double pointer is super ugly, so I think we should find some other way. We could use a struct for one thing, and a pointer for the other.

**Comment by steebchen** [comment]
@maaft Just FYI, there's already `SetOptional` – but it means `null` here and not `undefined`.

**Comment by matthewmueller** [comment]
Re-titled this issue to hopefully make it more clear. The problem in this issue is that it's dealing with "maybe filters".

@steebchen wrote a nice example

```go
var filter []prisma.IUserFilter
if email != nil {
  filter = append(filter, db.User.Email.Equals(*email))
}
if name != nil {
  filter = append(filter, db.User.Name.Equals(*name))
}
users, err := db.User.FindMany(filter).Exec(ctx)
```

**Comment by dustyhorizon** [comment]
> Re-titled this issue to hopefully make it more clear. The problem in this issue is that it's dealing with conditional filters. When you have a filter that may by present but it also may not be.
> 
> In today's API you would need to have conditionals for each possibility.
> 
> @steebchen wrote a nice potential solution:
> 
> ```go
> var filter []prisma.IUserFilter
> if email != nil {
>   filter = append(filter, db.User.Email.Equals(*email))
> }
> if name != nil {
>   filter = append(filter, db.User.Name.Equals(*name))
> }
> users, err := db.User.FindMany(filter).Exec(ctx)
> ```
> 
> Would that solve your problem @maaft?

Hey @matthewmueller, I am hitting the same use case as @maaft where I have "optional" filters that I would like to query for. As it stands right now as the "param"-related structs are not exposed I am unable to construct a filter array which I could pass into findMany().

Do advise when will @steebchen 's solution be released? I am using a similar method in Prisma 1.

**Comment by steebchen** [comment]
I'll post an update very soon.

**Comment by dustyhorizon** [comment]
> I'll post an update very soon.

Thats great to hear, thanks!

**Comment by dustyhorizon** [comment]
@steebchen Sorry to bump again but will the feature be available for .Update() too? I have a use case where I have a dynamic set of parameters to update an object. This is similar to the use case I am facing for .FindMany() also as described here.

**Comment by steebchen** [comment]
Yeah whatever we will do will work for dynamic update params as well. Do you mind sharing if you need to dynamically set or update optional values as well? Like a variable with a double pointer where one pointer stands for "undefined" (ignore field if nil) and one stands for "null" (sql IS NULL).

**Comment by dustyhorizon** [comment]
> Yeah whatever we will do will work for dynamic update params as well. Do you mind sharing if you need to dynamically set or update optional values as well? Like a variable with a double pointer where one pointer stands for "undefined" (ignore field if nil) and one stands for "null" (sql IS NULL).

Yes there is a requirement for that, as the optional value might be resolved at a later time within the system. However once set, there is no requirement to "unset" the optional value i.e. set to NULL. 

However I do foresee circumstances where there is a requirement to set that optional value to NULL as part of the workflow. Although a workaround would be to set that field to a fixed unused value and if it exists the application should treat it as null I guess?

**Comment by steebchen** [comment]
In the end, this is about what API we want to offer to the user and that's the tricky part at the same time.

Go doesn't really have nullability, and in this case you need two levels of nullability. Conventionally, libraries just use a pointer, but since sometimes you need to store both if something is undefined and null, so the first solution which pops into my mind is using a double pointer.
But it's not just about that, it's also about the different possible variations. If you have a string and we just offer one type, it gets ugly. This is why I can't think of anything else than providing all possible options as described in https://github.com/prisma/prisma-client-go/issues/203#issuecomment-690087450.

So, if you use pointers for nullability ("null", like a lot of libraries do), you can use `.XOptional` methods, if you use pointers for filtering ("undefined") you can use `.XMaybe` methods. I think this is already fine because some libraries do one or the other depending on context. For example, [gqlgen](https://github.com/99designs/gqlgen) input types use pointers for "undefined" while gqlgen output types use pointers for "null". In a case where you really need both, you can still use the third option with a double pointer `.XOptionalMaybe`.

Does that sound like a good solution for now @dustyhorizon?

**Comment by dustyhorizon** [comment]
> In the end, this is about what API we want to offer to the user and that's the tricky part at the same time.
> 
> Go doesn't really have nullability, and in this case you need two levels of nullability. Conventionally, libraries just use a pointer, but since sometimes you need to store both if something is undefined and null, so the first solution which pops into my mind is using a double pointer.
> But it's not just about that, it's also about the different possible variations. If you have a string and we just offer one type, it gets ugly. This is why I can't think of anything else than providing all possible options as described in [#203 (comment)](https://github.com/prisma/prisma-client-go/issues/203#issuecomment-690087450).
> 
> So, if you use pointers for nullability ("null", like a lot of libraries do), you can use `.XOptional` methods, if you use pointers for filtering ("undefined") you can use `.XMaybe` methods. I think this is already fine because some libraries do one or the other depending on context. For example, [gqlgen](https://github.com/99designs/gqlgen) input types use pointers for "undefined" while gqlgen output types use pointers for "null". In a case where you really need both, you can still use the third option with a double pointer `.XOptionalMaybe`.
> 
> Does that sound like a good solution for now @dustyhorizon?

Sounds like that should cover most of our use cases! As more users get onboarded with Prisma 2 on Go you could probably get more feedbacks with regards to this implementation.

Thanks for the hardwork!

**Comment by steebchen** [comment]
Does anyone have feedback about potential naming for these methods? I'm currently thinking `MaybeX`, so for example, `.SetMaybeEmail` or `.MaybeSetEmail`, but I'm not sure if that is clear enough.

**Comment by steebchen** [comment]
We have #300 in place to resolve this. I think we can all agree this would make sense for writing data, since often you just want to update something partially.

However, I'm not sure if it makes to add this for read/query parameters, since it could be easy to make mistakes and allow wrong queries. For example, if you query for a user by its id, but for some reason you use .MaybeID(x) and it is nil, the field would be ignored and ALL users would be queried for and returned.

For the people here who not only want the proposed behaviour not only in write operations but also for read/query operations, it would be great if you could elaborate on your exact use case and describe why you want or need this feature for query/read operations as well.

**Comment by steebchen** [comment]
For naming, instead of calling it maybe (pun intended), a better naming might be `SetOrIgnore` or `SetIfPresent`.

**Comment by dustyhorizon** [comment]
@steebchen my use case for this in read/query parameters is for performing query filtering i.e. something like get all users that has a field == "some value"; I am running gqlgen/grpc infront of prisma which specifies "optionals" and "required" parameters.

I understand that there may be a security concern with this as mentioned by you but I believe such validations / checks of presence of values should be done by the developer / whoever is writing code for that call so that Prisma is can still relatively flexible. Any thoughts?

**Comment by dustyhorizon** [comment]
> For naming, instead of calling it maybe (pun intended), a better naming might be `SetOrIgnore` or `SetIfPresent`.

Personally I feel that this naming is probably more consistent with the current `Set` for create/update related operations but not too sure what would be appropriate for read/query related operations (if you guys are considering implementing them too!)

**Comment by steebchen** [comment]
I agree it would be more consistent, but I feel like "maybe" is really unclear at what it does, whereas IfPresent would communicate more clearly that it would Set the value if present or OrIgnore would mean ignore if the pointer is nil.

**Comment by steebchen** [comment]
I'd love your opinion as well if you may need this feature: @hi019 @jemilezzet @tarrencev @maaft @zafhiel

**Comment by hi019** [comment]
Hi! At the moment I don't have a need for the proposed optional methods, however it's for sure something I could see being useful in the future. About query parameters, I think they should exist. I agree that accidentally omitting an ID from a query could be dangerous, but I think that should be left to the user and not be a barrier for implementation.

**Comment by maaft** [comment]
@steebchen Hello there! I must admit that we've switched our database from SQL to a graph database (dgraph-graphql) but if we were still using SQL, I think that having these for query parameters as well would be nice.
