### ISSUE TITLE
Raw query Insert?

### ISSUE THREAD

**Issue by OAyomide** [prisma/prisma-client-go#277]
I tried to use the raw API and i kept a json unmarshalling error. Is there something i am missing?
below is an example of my query:
```go
var out []interface{}
	err = prod.DB.QueryRaw(`INSERT into "Product" (id, name) VALUES($1,$2)`, someBody.ID, someBody.Name,).Exec(context.Background(), &out)
```

the error is:
```text
could not decode result.QueryRaw: unexpected end of JSON input
```

its driving me insane

**Comment by steebchen** [comment]
What database are you using? Can you make sure the SQL query itself is valid?
I discovered [another bug](https://github.com/prisma/prisma-client-go/issues/278) which most likely results in the actual error message being suppressed. I'm already working on it and will report back.

---

On another note, I'm wondering why you use a raw query for this instead of just using the type-safe `CreateOne`, would be great if you could let me know why you need to use raw.

**Comment by steebchen** [comment]
I have improved error handling via #279. Can you please get the latest version via `go get github.com/prisma/prisma-client-go@master`, run `go run github.com/prisma/prisma-client-go generate` and try again? It should hopefully give a clearer error message.

**Comment by steebchen** [comment]
One more thing: it's recommended to use `ExecuteRaw` instead of `QueryRaw`, since you are not querying for things but `INSERT` will return a "rows affected count". I'll clarify this in the docs via #282.

**Comment by OAyomide** [comment]
Yeah you're right. ```ExecuteRaw``` is the best choice. but i was curious about doing ```Insert``` on ```QueryRaw```

**Comment by steebchen** [comment]
Closing for now – please re-open if there should be still an issue with the go client.
