### ISSUE TITLE
export query interface/parameters to allow dynamic query building

### ISSUE THREAD

**Issue by dustyhorizon** [prisma/prisma-client-go#344]
Hello, I noticed that query parameters are not exported which restricts query building to only XIfPresent methods.

Is it possible to export the interfaces/structs used to build the query so that we can constantly append the query to a slice of parameters and then do a variadic spread of the slice onto the find/update method itself?

e.g.

```
currentUser := getUserFromCtx(ctx)
createParams := []db.UserSetParams{}

if currentUser.Role == foo {
  createParams = append(createParams, bar)
} else {
  createParams = append(createParams, baz)
}

db.User.CreateOne(createParams...)
```

This would allow for even greater flexibility in building queries dynamically in addition to the new XIfPresent methods.

Thanks!

**Comment by steebchen** [comment]
We do want to export those methods, but want to think of proper naming first. Some of those types might not have ideal names right now, and we don't want to make breaking changes around those types if we can avoid it.

As a temporary workaround, you can create a new go file in the package where the Prisma client is generated (default is `db`), and manually export the types you need to use by re-exporting the type via `type IUserSetParams = iUserSetParams`.

**Comment by dustyhorizon** [comment]
> We do want to export those methods, but want to think of proper naming first. Some of those types might not have ideal names right now, and we don't want to make breaking changes around those types if we can avoid it.
> 
> As a temporary workaround, you can create a new go file in the package where the Prisma client is generated (default is `db`), and manually export the types you need to use by re-exporting the type via `type IUserSetParams = iUserSetParams`.

Ah have not thought of this, thanks for the workaround!

**Comment by steebchen** [comment]
Sure; just remember that we will change the names at some point.

**Comment by steebchen** [comment]
For the export of the interfaces to build dynamic queries, I’m not sure what to name them. There are also major differences to the JS client.

There are basically two major types, one to query for something (find or building up there “where” part for update/delete) and one to write something (create & update).

So we could name them something like:

```
<Model>FindParams
<Model>SetParams
```

Other options could be Read/Write or Query/Mutate. Find Set is what I did previously, for Read/Write I don’t like the read so much since I’d rather have it called “query” or “find”).
Another option could be Query/Mutate, I like this one, but maybe reminds too much of GraphQL?

**Comment by robojones** [comment]
How about `where` for queries and `set` for create and update?
