### ISSUE TITLE
Quickstart errors

### ISSUE THREAD

**Issue by alechp** [prisma/prisma-client-go#475]
### Error 1 - "table `main.Post` does not exist in the current database
![Screen Shot 2021-05-14 at 8 24 04 AM](https://user-images.githubusercontent.com/3058939/118292725-c6956500-b48d-11eb-86d0-0825fdef19e8.png)

Prisma has populated the SQLite db:
![Screen Shot 2021-05-14 at 8 26 43 AM](https://user-images.githubusercontent.com/3058939/118293066-1ffd9400-b48e-11eb-980e-4a3b4ab545a1.png)

---

### Error 2 (easy fix) - cannot find package "." in: ...demo/db
![Screen_Shot_2021-05-14_at_8 02 21_AM](https://user-images.githubusercontent.com/3058939/118292800-db71f880-b48d-11eb-9c6f-09d2d9b4a53b.png)

**This is resolved by updating import in main.go from "demo/db" to "demo/prisma/db"**
 
![Screen_Shot_2021-05-14_at_7 59 57_AM](https://user-images.githubusercontent.com/3058939/118292840-e7f65100-b48d-11eb-8799-287e1fe13be1.png)

**Comment by steebchen** [comment]
Thanks, I have fixed the second one. However for the first one, I think there is some issue with your database, because it simply means the table you want to access just doesn't exist in the database. It's most likely something wrong with introspection, or the database differs, or something went wrong with migrations. Please consider commenting with more details (if you're using migrate or introspection, your version, what database, your schema file, etc.) or opening a GitHub discussion.

**Comment by trading-peter** [comment]
I got the same `"table main.Post does not exist in the current database` error as Alec. All I did is copy+pasting+executing the commands from the quick start. So it seems some is indeed off with those instructions. I can't point out what though.

**Comment by steebchen** [comment]
Hm interesting. It would be great if both of you could run `go run github.com/prisma/prisma-client-go db push` again and see if it works. If it doesn't, please send the output of the previous command.

**Comment by alechp** [comment]
@steebchen This was the state of the dev.db sqlite file was generated before running the command:

![Screen Shot 2021-05-18 at 5 53 31 AM](https://user-images.githubusercontent.com/3058939/118654404-63614680-b79d-11eb-9630-52c23d950207.png)

Error after running `go run github.com/prisma/prisma-client-go db push`:
![Screen Shot 2021-05-18 at 5 55 46 AM](https://user-images.githubusercontent.com/3058939/118654721-b2a77700-b79d-11eb-8fe1-7cd95a4bd10d.png)
```
package github.com/prisma/prisma-client-go: no Go files in /Users/alechp/Code/roundtabletg/prisma-go/demo/vendor/github.com/prisma/prisma-client-go
```

**Comment by steebchen** [comment]
It seems there are two different issues, one being the error with the database on runtime and one where the command fails completely with this Go error. The latter seems unrelated though, maybe related to vendoring. If you keep running into this, maybe it's best to open a new issue. I'll investigate the former error though since that's what this issue is about.

**Comment by alechp** [comment]
@steebchen When you follow the current quickstart step-by-step, what results do you see?

**Comment by steebchen** [comment]
I indeed get the same error when doing a from-scratch project. I'll look into it, thanks for reporting and sorry for dismissing too early.

**Comment by steebchen** [comment]
It looks like there is a bug related to a relative path issue. That means there was a dev.db file in prisma/ from `db push` and in the root directory from the client.

Please move the prisma.schema file into the root, run `db push` again and it should work.

For now, I have adapted the quickstart so that the prisma schema is created in the root.

I will close this and will put further discussion into a more clear issue for planning at #482.
