### ISSUE TITLE
Case Style Error - FieldNotFoundError

### ISSUE THREAD

**Issue by zafhiel** [prisma/prisma-client-go#58]
Hi guys!

Today I found this error: **field_name: "fieldTest", inner: FieldNotFoundError**

```shell
Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findOneUser", inner: ObjectValidationError { object_name: "User", inner: FieldValidationError { field_name: "fieldTest", inner: FieldNotFoundError } } } })
```

# The Context

My file scheme.prisma the field **field_test** in _snake case_

```prisma
model User {
  id          String   @default(cuid()) @id @unique
  createdAt   DateTime @default(now())
  email       String   @unique
  name        String?
  age         Int?
  field_test  Int?
  posts       Post[]
}
```

After lift create the table is created with the field **field_test** in _snake case_, fine!

```sql
create table User
(
	age INTEGER,
	createdAt DATE default '1970-01-01 00:00:00' not null,
	email TEXT default '' not null,
	field_test INTEGER,
	id TEXT not null key,
	name TEXT
);

```
After photon is generated I think the problem is json tag was created in _camelcase_
```go
type user struct {
	ID          string   `json:"id"`
	CreatedAt   DateTime `json:"createdAt"`
	Email       string   `json:"email"`
	Name        *string  `json:"name"`
	Age         *int     `json:"age"`
	FieldTest   *int     `json:"fieldTest"`
}
```

 thanks! :hugs:

**Comment by steebchen** [comment]
Thanks for the bug report! For now, I'd recommend to just use `camelCase` field names, i.e. you could use `fieldTest` instead of `field_test`. Since Go uses camelCase/UpperCamelCase, the Go Code would look the same either way.

While this is currently a bug which I will fix when I'm back at work (in 1-2 weeks), it also opens up a whole new discussion of how the prisma schema can or should constrain the user to a specific casing scheme.

I'd like to know if you have strong opinions about casing in the schema. Would you prefer `snake_case` over `camelCase`? If we would force you to use `camelCase` everywhere, would you be okay with this solution? While it constrains you more, it also prevents you from mixing differently cased fields. For example, now your schema has `createdAt` and `field_test`, which is inconsistent.

**Comment by steebchen** [comment]
Related specs issue about schema field and attribute naming: https://github.com/prisma/specs/issues/146

**Comment by zafhiel** [comment]
> Thanks for the bug report! For now, I'd recommend to just use `camelCase` field names, i.e. you could use `fieldTest` instead of `field_test`. Since Go uses camelCase/UpperCamelCase, the Go Code would look the same either way.
> 
> While this is currently a bug which I will fix when I'm back at work (in 1-2 weeks), it also opens up a whole new discussion of how the prisma schema can or should constrain the user to a specific casing scheme.
> 
> I'd like to know if you have strong opinions about casing in the schema. Would you prefer `snake_case` over `camelCase`? If we would force you to use `camelCase` everywhere, would you be okay with this solution? While it constrains you more, it also prevents you from mixing differently cased fields. For example, now your schema has `createdAt` and `field_test`, which is inconsistent.

Thanks @steebchen I prefer camelCase and I agree with your solution!
