### ISSUE TITLE
Recommended approach for multiple generators

### ISSUE THREAD

**Issue by abelanger5** [prisma/prisma-client-go#835]
We'd like to re-use our prisma schema and folder across multiple services -- we currently have a Prisma schema generated via:

```prisma
generator client {
  provider = "prisma-client-js"
}
```

But to generate the Go client, we need to change this to:

```prisma
generator client {
  provider = "go run github.com/prisma/prisma-client-go"
}
```

Is there a recommended approach for managing/switching between the providers? Can file this in the prisma repo if necessary.  

According to the [Prisma docs](https://www.prisma.io/docs/concepts/components/prisma-schema/generators):

> A Prisma schema can have one or more generators

But I don't see any support for multiple generators in the docs.

**Comment by steebchen** [comment]
Most users just use a single client, which is why there's not so much about it in the docs. However, it's certainly possible, but it does introduce a few caveats.

You need to run this with NodeJS/npm as I believe the other way round currently doesn't work, making NodeJS/npm the source of truth for the Prisma versions and using it for migrations.

For example, this should work:

```prisma
datasource db {
  // could be postgresql or mysql
  provider = "sqlite"
  url      = "file:dev.db"
}

generator go {
  provider = "go run github.com/prisma/prisma-client-go"
}

generator js {
  provider = "prisma-client-js"
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  published Boolean
  desc      String?
}
```

I also just tried setting the provider dynamically, but unfortunately that [doesn't work at this time](https://github.com/prisma/prisma/issues/19368).

**Comment by abelanger5** [comment]
Ah, got it - this worked 👍 

It wasn't clear to me that the generator block could be named something other than `generator client`.

**Comment by steebchen** [comment]
@abelanger5 You can also set it dynamically, I was mistaken that it's not supported:

```prisma
datasource db {
  // could be postgresql or mysql
  provider = "sqlite"
  url      = "file:dev.db"
}

generator go {
  provider = env("PROVIDER")
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  published Boolean
  desc      String?
}
```

```
export PROVIDER="go run github.com/prisma/prisma-client-go"
❯ npx prisma generate
Prisma schema loaded from schema.prisma

✔ Generated Prisma Client Go to ./db in 1.01s
```
